name: Test install
on:
  push:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Get Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install requirements
        run: pip install magical-cloud-dictionary
      - name: Test minimal example
        run: python -c "from magical_cloud_dictionary import Magic;assert Magic('test').get('answer') == 42;"
